### ISSUE TITLE
Test_Toolkit: Deprecated compliance check

### ISSUE THREAD

**Issue by kThorsager** [BHoM/Test_Toolkit#138] opened 2020-02-10 15:24 UTC
#### Description:
If a toolkit is making use of a `Deprecated` method, that should considered a failed compliance check.

**Comment by FraserGreenroyd** [comment] 2020-02-10 15:26
Duplicate of https://github.com/BHoM/Test_Toolkit/issues/25 - will not action

**Closed by FraserGreenroyd** 2020-02-10 15:26 UTC
Labels: type:feature
